# numpy 
[numpy](http://www.runoob.com/numpy/numpy-statistical-functions.html)

In [2]:
import numpy as np


In [11]:
a = np.array([1,2,3])
print(a)

print(a.shape)

[1 2 3]
(3,)


In [8]:
a = np.array([1,2,3,4,5,6]).reshape(2,3)
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [14]:
a=(3,)
b=(3)
print(type(a))
print(type(b))
print(a)
print(b)


<class 'tuple'>
<class 'int'>
(3,)
3


# 创建

In [17]:
#指定大小,未初始化
x=np.empty([3,2],dtype=int)
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
# 默认为浮点数
x=np.zeros([3,2],dtype=int)
print(x)
x=np.zeros([3,2])
print(x)

x=np.ones([3,2])
print(x)

[[0 0]
 [0 0]
 [0 0]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
#已有创建
n = np.array([1,2,3])
print(n)
# M 快捷 Markdown
# Y 快捷 code
n = np.asarray([1,2,3])
print(n)

[1 2 3]
[1 2 3]


## 数值范围创建

In [28]:
#未指定类型,根据输入类型
a = np.arange(0,10,1)
print(a)
a = np.arange(0.,10,1)
print(a)
a = np.arange(10)
print(a)
a = np.arange(10,20,5)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]
[10 15]


In [32]:
x = np.linspace(10,100,5)
print(x)
x = np.linspace(10,100,5,endpoint=False)
print(x)

[ 10.   32.5  55.   77.5 100. ]
[10. 28. 46. 64. 82.]


In [39]:
y = np.logspace(1,3,num=3,base=2)
print(y)

[2. 4. 8.]


# 随机数创建
https://www.cnblogs.com/lemonbit/p/6864179.html

In [43]:
# 0<=x<1
x = np.random.rand(9)
print(x)
x = np.random.rand(2,3,4)
print(x)

[0.88406919 0.49198972 0.47541781 0.39963491 0.13005213 0.38158067
 0.30534001 0.00766936 0.23977698]
[[[0.26901666 0.0678413  0.81633089 0.52092997]
  [0.25471144 0.68316983 0.11761108 0.31707516]
  [0.06715052 0.13632326 0.29402092 0.42071678]]

 [[0.26376685 0.24538609 0.77289597 0.68736087]
  [0.25336537 0.80363742 0.85356151 0.84131533]
  [0.53664871 0.82810375 0.72893539 0.07074901]]]
